---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Key/value pairs to be added to the game's client_config.yml file
# These values will be replaced at the end of create/update of
# the feature's CloudFormation stack.

achievements_api_gateway_base_url: "{{AWSGAMEKIT::CFNOUTPUT::AchievementsApiGatewayBaseUrl}}"
achievements_region: "{{AWSGAMEKIT::CFNOUTPUT::AchievementsRegion}}"
achievements_icons_base_url: "{{AWSGAMEKIT::CFNOUTPUT::AchievementsIconsCloudFrontBaseUrl}}"
